# Generated by Django 4.2.6 on 2023-10-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.CharField(max_length=25)),
                ("title", models.CharField(max_length=50)),
                ("image", models.ImageField(blank=True, upload_to="%y/%m/")),
                ("relese_date", models.CharField(max_length=25)),
                ("description", models.TextField()),
            ],
        ),
    ]
