# Generated by Django 4.2.6 on 2023-10-10 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0004_alter_gamecontent_release_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamecontent",
            name="description",
        ),
    ]
