# Generated by Django 4.2.6 on 2023-10-11 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0009_alter_gamecontent_rate_alter_musiccontent_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="rate",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
    ]
