# Generated by Django 4.2.6 on 2023-10-11 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0010_alter_comment_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamecontent",
            name="rate",
        ),
        migrations.RemoveField(
            model_name="moviecontent",
            name="rate",
        ),
        migrations.RemoveField(
            model_name="musiccontent",
            name="rate",
        ),
    ]
